version: "3.9"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongodb:dev_password@mongo:27017/
      PORT: 4000
      JWT_SECRET: fc9OLIN9l2WT+wJWOf0WV96AmK6SzbiXjOErtj3pIGwOBRTCa2FNweT8jgvrMhQW

    volumes:
      - ./src:/app/src
    command: yarn dev

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: dev_password

