version: "3.9"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongodb:dev_password@mongo:27017/
      PORT: 4000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: dev_password

